In [1]:
import numpy as np 

## Assignment 2A

In [2]:
from A.graph import constructAdjM, compute_principle_left_eigen_vector, constructProbTransMatrix, get_ranks, power_iteration

In [3]:
V, E, adjM = constructAdjM("input.txt")

for r in adjM:
    print(r)

[0, 1, 0, 0]
[1, 0, 1, 0]
[0, 1, 0, 1]
[0, 0, 1, 0]


In [4]:
P = constructProbTransMatrix(V, adjM)

for r in P:
    print(r)

[0.225 0.325 0.225 0.225]
[0.275 0.225 0.275 0.225]
[0.225 0.275 0.225 0.275]
[0.225 0.225 0.325 0.225]


In [5]:
PI = compute_principle_left_eigen_vector(P)
PI

array([0.25, 0.25, 0.25, 0.25])

In [6]:
get_ranks(PI)

Rank 1:= Page 4
Rank 2:= Page 3
Rank 3:= Page 2
Rank 4:= Page 1


## Power Iteration method

In [7]:
x, t = power_iteration(V, P, threshold=1e-9)

In [8]:
print(f"Converges after timesteps: {t}")
print(f"PI: {x}")


Converges after timesteps: 16
PI: [[0.23809524 0.26190476 0.26190476 0.23809524]]


## Assignment 2B