In [11]:
import numpy as np 
import scipy.linalg

In [12]:
P = np.array([[1./6, 2./3, 1./6], 
              [5./12, 1./6, 5./12],
              [1./6, 2./3, 1./6]])

In [13]:
v, V = np.linalg.eig(P.T)


In [22]:
V

array([[-4.68292906e-01, -7.07106781e-01,  4.08248290e-01],
       [-7.49268649e-01,  3.18583790e-17, -8.16496581e-01],
       [-4.68292906e-01,  7.07106781e-01,  4.08248290e-01]])

In [23]:
left_vec = V[:, v.argmax()].T
left_vec = left_vec / left_vec.sum()
left_vec

array([0.27777778, 0.44444444, 0.27777778])

In [20]:
scipy.linalg.eig(P, left=True, right=False)

(array([ 1.00000000e+00+0.j, -5.70612907e-17+0.j, -5.00000000e-01+0.j]),
 array([[-4.68292906e-01, -7.07106781e-01,  4.08248290e-01],
        [-7.49268649e-01,  3.18583790e-17, -8.16496581e-01],
        [-4.68292906e-01,  7.07106781e-01,  4.08248290e-01]]))

In [25]:
A = 3 * [3 * [0]]

A

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [26]:
V = 4 
E = 6 

In [28]:
adjM = V * [V * [0]]

In [29]:
S = input()

In [31]:
S.split()

['3', '4', '5']