In [1]:
import numpy as np 
from src.graph import constructAdjM, constructProbTransMatrix

In [2]:
V, E, adjM = constructAdjM("input.txt")
print(adjM)

[[0, 1, 0, 0], [1, 0, 1, 0], [0, 1, 0, 1], [0, 0, 1, 0]]


In [8]:
P_random = constructProbTransMatrix(V, adjM, random_teleport=False)
P_random

[[0, 1.0, 0, 0], [0.5, 0, 0.5, 0], [0, 0.5, 0, 0.5], [0, 0, 1.0, 0]]

In [9]:
eigVals, eigVecs = np.linalg.eig(P_random)

In [10]:
eigVals, eigVecs

(array([-1. , -0.5,  1. ,  0.5]),
 array([[-0.5       , -0.63245553,  0.5       , -0.63245553],
        [ 0.5       ,  0.31622777,  0.5       , -0.31622777],
        [-0.5       ,  0.31622777,  0.5       ,  0.31622777],
        [ 0.5       , -0.63245553,  0.5       ,  0.63245553]]))

In [14]:
left_vec = eigVecs[:, eigVals.argmax()]
left_vec /= left_vec.sum()

In [15]:
left_vec

array([0.25, 0.25, 0.25, 0.25])